AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Email Sender Project

Globals:
  Function:
    Timeout: 3
    LoggingConfig:
      LogFormat: JSON

Resources:
  SendEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: send.lambda_handler  # Entry point for the function in app.py
      Runtime: python3.12
      Architectures:
        - x86_64
      CodeUri: email_sender/  # Update with the directory where your Lambda function code is stored
      Environment:
        Variables:
          AWS_REGION: "us-east-1"  # Adjust to your region
      Events:
        SendEmailApi:
          Type: Api
          Properties:
            Path: /send-email  # URL path for the endpoint
            Method: post       # HTTP method for the endpoint

      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: "*"  # This allows sending email to any verified email in SES

Outputs:
  SendEmailApi:
    Description: API Gateway endpoint URL for SendEmail function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/send-email/"
  SendEmailFunction:
    Description: SendEmail Lambda Function ARN
    Value: !GetAtt SendEmailFunction.Arn
  SendEmailFunctionIamRole:
    Description: IAM Role for SendEmail function
    Value: !GetAtt SendEmailFunctionRole.Arn